#!/bin/sh

SHORTDIR=${PWD##*/}
SHORTDIR=${SHORTDIR//./_dot_}
SHORTDIR=${SHORTDIR//:/_colon_}
TMPDONE=".tmp_git_diff_done_$SHORTDIR"
MSG='q to exit, r to force reload: '

git diff | cat
printf "$MSG"
while read -n 1 line
do
    printf "\n$MSG"
    [[ $line = q ]] && touch "$TMPDONE" && tmux detach && break
    [[ $line = r ]] && tmux detach && break
done