#!/bin/sh

# Generates a series of diffs from a patch diff by starting from a diff consisting of only the first hunk,
# and where each diff has one more hunk than the one before it. For use in interactive binary search

COUNT=0;
STARTED=0;
rm -v .tmp_split_patch_cumulative .spc_*
if [[ -z $1 ]]; then
	read file
	echo $file > .tmp_split_patch_cumulative;
fi
	# echo "$line" | egrep '[0-9]+(,[0-9]+)?c[0-9]+(,[0-9]+)?' > /dev/null
	# if [ $? -eq 0 ]; then
 #   	    echo "$line is $COUNT"
 #   	    cp .tmp_split_patch_cumulative ".spc_$COUNT"
 #   	    STARTED=1
 #   	fi
	# echo "$line" >> .tmp_split_patch_cumulative
 #   	((COUNT++))