'\" t
.\"     Title: cdiff
.\"    Author: Ville Skytt\(:a
.\" Generator: DocBook XSL Stylesheets v1.75.2 <http://docbook.sf.net/>
.\"      Date: 11/14/2012
.\"    Manual: User Commands
.\"    Source: cdiff
.\"  Language: English
.\"
.TH "CDIFF" "1" "11/14/2012" "cdiff" "User Commands"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
cdiff \- a wrapper tool for colordiff
.SH "SYNOPSIS"
.HP \w'\fBcdiff\fR\ 'u
\fBcdiff\fR {\fIURL|FILE\fR}
.SH "DESCRIPTION"
.PP
cdiff
is a wrapper for colordiff and will add colour to a diff given in a URL or a file, e\&.g\&.
.sp
.if n \{\
.RS 4
.\}
.nf
cdiff http://some\&.url\&.com/foo/thing\&.patch
.fi
.if n \{\
.RE
.\}
.PP
It also adds support for reading gzip, bzip2, xz, and lzma compressed diffs, and like colordiff, also supports reading diffs from standard input if URL or a filename is not specified\&.
cdiff
pipes colordiff\*(Aqs output through less \-R\&.
.SH "SEE ALSO"
.PP
cdiff
is part of the colordiff package, which should be consulted for further reference\&.
.SH "AUTHORS"
.PP
\fBVille Skytt\(:a\fR
.RS 4
cdiff author
.RE
.PP
\fBDave Ewart\fR
.RS 4
colordiff author, packager for colordiff/cdiff
.RE
